#!/bin/bash

echo "CMAKE_CONFIGURE_ARGS=$CMAKE_CONFIGURE_ARGS -DCMAKE_OSX_DEPLOYMENT_TARGET=$TARGET_OSX_VERSION" >> $GITHUB_ENV
echo "LINK_FLAGS=$LINK_FLAGS -mmacosx-version-min=$TARGET_OSX_VERSION" >> $GITHUB_ENV
echo "C_XX_FLAGS=$C_XX_FLAGS -mmacosx-version-min=$TARGET_OSX_VERSION" >> $GITHUB_ENV
