#!/bin/bash
export HOMEBREW_NO_INSTALL_CLEANUP=1
export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
brew update
brew install llvm@22 ninja

echo "CMAKE_CONFIGURE_ARGS=$CMAKE_CONFIGURE_ARGS -DCMAKE_OSX_DEPLOYMENT_TARGET=$TARGET_OSX_VERSION" >> $GITHUB_ENV
echo "LINK_FLAGS=-mmacosx-version-min=$TARGET_OSX_VERSION" >> $GITHUB_ENV
echo "C_XX_FLAGS=-mmacosx-version-min=$TARGET_OSX_VERSION" >> $GITHUB_ENV
